### ISSUE TITLE
CLSID_UpdateSessionOrchestrator is same?

### ISSUE THREAD

**Issue by IMnewer** [itm4n/UsoDllLoader#3]
The CLSID_UpdateSessionOrchestrator is same in different system? For example win10 , server2008 and win7.

**Comment by itm4n** [comment]
The USO service was introduced in Windows 10 / Server 2016 (c.f. README). In other words, this COM object doesn't exist on older versions of Windows.

**Comment by IMnewer** [comment]
OK, ths
